### ISSUE TITLE
0 plugins

### ISSUE THREAD

**Issue by troydm** [banyan/Vimpusher#27]
hello! I've registed my .vimrc file and specified correct https://github.com/troydm/dotvim/blob/master/.vimrc path

http://www.vimpusher.com/troydm

however vimpusher panels says that i have 0 plugins installed, i'm using vundle to manage plugins

**Comment by banyan** [comment]
hi! thanks for register.
I'll check it out.

**Comment by banyan** [comment]
@troydm 

The job worker was not worked and now I fixed.
Thanx for letting me know :octocat:
